name: 0. Testing Login to WandB

on:
  workflow_dispatch: # Allows manual execution only

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python  
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip' # caching pip dependencies
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Login to WandB
          env:
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          run: wandb login $WANDB_API_KEY